### ISSUE TITLE
editable="false" broken in Playground

### ISSUE THREAD

**Issue by RoboErikG** [google/blockly#500]
It looks like setting editable="false" in the xml for a block is broken.

To reproduce,
- drag an addition block in to the workspace
- export to xml
- edit the xml to include editable="false" in the addition block
- import from xml

utils.js:45 Uncaught TypeError: Cannot read property 'getAttribute' of undefinedBlockly.addClass_ 
@ utils.js:45 Blockly.Field.updateEditable
@ field.js:191Blockly.Block.setEditable
@ block.js:563Blockly.BlockSvg.setEditable
@ block_svg.js:947Blockly.Xml.domToBlockHeadless_
@ xml.js:523Blockly.Xml.domToBlock
@ xml.js:336Blockly.Xml.domToWorkspace
@ xml.js:302fromXml
@ playground.html:136onclick
@ playground.html:353

**Comment by NeilFraser** [comment]
Can't recreate.  This should have been fixed a week ago:
https://github.com/google/blockly/commit/e03a4a9e30c12bc003735622cfb00b9f70d68e69

Can you confirm that your seeing this on the latest version?

**Comment by RoboErikG** [comment]
Maybe we just need a rebuild of the demos. I'm seeing it on https://blockly-demo.appspot.com/static/tests/playground.html

**Comment by NeilFraser** [comment]
Confirming that the bug is visible in blockly-demo, but not in head of master or develop.  Will disappear next time we push.

**Comment by zubairq** [comment]
I'm still seeing this error in the latest blockly zip release... Has this fix been pushed?

**Comment by zubairq** [comment]
I see that field.js has the latest changes:

Blockly.Field.prototype.callValidator = function(text) {
  var classResult = this.classValidator(text);
  if (classResult === null) {
    // Class validator rejects value.  Game over.
    return null;
  } else if (classResult !== undefined) {
    text = classResult;
  }
  var userValidator = this.getValidator();
  if (userValidator) {
    var userResult = userValidator.call(this, text);
    if (userResult === null) {
      // User validator rejects value.  Game over.
      return null;
    } else if (userResult !== undefined) {
      text = userResult;
    }
  }
  return text;
};
 so could it be that blockly_compressed.js has not been updated?
